environment                    = "homologation"
vpc_cidr                       = "10.20.0.0/16"
cluster_endpoint_allowed_cidrs = ["0.0.0.0/0"] # restringir antes do deploy real
node_min_size                  = 2
node_desired_size              = 2
node_max_size                  = 4
traefik_chart_version          = "41.4.0"
metrics_server_chart_version   = "3.13.0"
datadog_chart_version          = "3.215.1"
auth_function_url              = "https://REPLACE_ME.lambda-url.sa-east-1.on.aws/"
