apiVersion: v1
kind: Secret
metadata:
  name: oficina-app-secret
  namespace: oficina
type: Opaque
stringData:
  DB_USERNAME: oficina
  DB_PASSWORD: oficina123
  JWT_SECRET: oficinaMecanicaSecretKeyForJWTTokenGeneration2024
